=begin
#Ruler API

#Ruler API is a flexible API for rules. Originally designed for FIRST Robotics Competition, it is flexible in nature to allow for any program to use it.

OpenAPI spec version: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-beta3

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::GetRuleApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GetRuleApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::GetRuleApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GetRuleApi' do
    it 'should create an instance of GetRuleApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::GetRuleApi)
    end
  end

  # unit tests for get_rule
  # Returns the content of a rule.
  # @param rule_id Rule ID to get
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'get_rule test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
